### PR TITLE
Refactored object inspec checks

### PR DESCRIPTION
**Pull request by narengan**

### CODE REVIEW

**Comment by narengan** [comment]
@jjasghar  Can I get a quick merge/check on this PR? its refactoring the checks so that we can skip the files that dont exist on our system

**Comment by narengan** [comment]
@jjasghar Can you merge it today when you get the time? thanks!

**Comment by jjasghar** [comment]
As of this morning I've enforcing the DCO for this repo.

With our new policy please use the [DCO signing process](https://discourse.chef.io/t/a-developer-certificate-of-origin-dco-is-now-required-with-code-contributions/9579).

For a [detailed description](http://stackoverflow.com/questions/13457203/how-to-add-the-signed-off-by-field-in-the-git-patch) or you can just do:

```
$ git commit -s
$ #Or
$ git commit --signoff
```

If you already have the commit, use git commit --amend or git rebase -i to edit your commit message, and add the above signoff line.

Or if you want a more perminant option the following is a way to set it forever:

```bash
$ git config commit.gpgsign true
```

Can you update your commit with this please?

**Comment by narengan** [comment]
@jjasghar  sure ill do it right away

**Comment by narengan** [comment]
@jjasghar does that look good?

**Comment by jjasghar** [comment]
thanks! 🤘

**Pull request merged**
