### PR TITLE
Use new InSpec profile structure

### PR DESCRIPTION
**Pull request by chris-rock**
This is a preparation for the time when https://github.com/chef/inspec/pull/314 has been accepted and merged.

### CODE REVIEW

**Comment by jjasghar** [comment]
Looks straight forward. :+1:

**Comment by chris-rock** [comment]
@jjasghar chef/inspec#314 is merged and will be available with the next release of InSpec

**Comment by chris-rock** [comment]
@jjasghar Anything that needs to be fixed?

**Comment by jjasghar** [comment]
nope, this is good to go!

**Pull request merged**
